//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public DONHANG()
        {
            this.DONHANGCHITIETs = new HashSet<DONHANGCHITIET>();
        }
    
        public int MaDH { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public decimal TongTien { get; set; }
        public int MAKH { get; set; }
        public int ThanhToan { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual ICollection<DONHANGCHITIET> DONHANGCHITIETs { get; set; }
    }
}
