//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.DONHANGCHITIETs = new HashSet<DONHANGCHITIET>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public string Link { get; set; }
        public Nullable<int> MATHELOAI { get; set; }
        public Nullable<int> MANHASANXUAT { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<decimal> SoLuotXem { get; set; }
        public Nullable<int> bixoa { get; set; }
    
        public virtual ICollection<DONHANGCHITIET> DONHANGCHITIETs { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
    }
}
