//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Web_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAMCHITIET
    {
        public int ID { get; set; }
        public int MASP { get; set; }
        public string ManHinh { get; set; }
        public string HeDieuHanh { get; set; }
        public string CamSau { get; set; }
        public string CamTruoc { get; set; }
        public string CPU { get; set; }
        public string Ram { get; set; }
        public string BoNhoTrong { get; set; }
        public string TheSim { get; set; }
        public string HoTroTheNho { get; set; }
        public string DungLuongPin { get; set; }
        public string ChucNangKhac { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<decimal> Gia { get; set; }
    }
}
